### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by Otoru** [EvoluxBR/greenswitch#53]
In the example file for creating an Outbound ESL Server there is a [TODO](https://github.com/EvoluxBR/greenswitch/blob/aefd9f5398a21d50b3cba462a136cfa953ad5c4e/examples/outbound_socket_example.py#L28) to move the logic of `self.safe_run()` into the library. However, I understood that it is within this function where we implement the activity we want to perform.

Does this whole refer to moving the exception handling into the lib? I ask the question because I am interested in contributing to the library.

**Comment by italorossi** [comment]
That was implemented here https://github.com/EvoluxBR/greenswitch/commit/724c47190de15d01a7ae3b4259bac732a65e1933

The core is now 'safe' so in case of an error in the user application that handles the call we'll properly decrease the call and connection count. This is done here: https://github.com/EvoluxBR/greenswitch/commit/724c47190de15d01a7ae3b4259bac732a65e1933#diff-ee06282fd7af64bb07f4f2ab1cbab207R515

I'd say we can just change the comment there instead of a TODO to just a comment instructing the user that exceptions may occur and it's the user's responsibility to handle then and act according to the application logic.

**Comment by Otoru** [comment]
I understand, I think the issue can be closed, since this is just a matter of documentation.
